### PR TITLE
STOR-1402: Chore: update libraries in all operators [4.15]

### PR DESCRIPTION
**Pull request by dobsonj**
/cc @openshift/storage

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

**Comment by adambkaplan** [comment]
Snyk scan picked up an item in a dependency. Do we need a separate PR to mark it as ignorable?

**Comment by dobsonj** [comment]
> Snyk scan picked up an item in a dependency. Do we need a separate PR to mark it as ignorable?

Those items aren't new or related to this PR though, I see the same in another PR:

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-csi-driver-shared-resource-operator-master-security

From @coreydaley 's comment in https://github.com/openshift/release/pull/44557#issuecomment-1769194652 though it's expected the synk job won't pass yet.

**Pull request merged**
