### PR TITLE
OCPBUGS-44616: Mark csi-driver-shared-resource-operator obsolete

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1823

/cc @openshift/storage @adambkaplan @sayan-biswas

### CODE REVIEW

**Review by sayan-biswas — APPROVED** [review]

**Review by sayan-biswas — APPROVED** [review]

**Comment by dobsonj** [comment]
Blah... I already removed the presubmits in https://github.com/openshift/release/pull/57376, don't understand why tide expects that job to succeed.

**Comment by dobsonj** [comment]
Just seeing if a valid bug makes any difference
/retitle OCPBUGS-44616: Mark csi-driver-shared-resource-operator obsolete

**Pull request merged**
