### PR TITLE
BUILD-256: nuke manifest folder (those live under assets in CSO)

### PR DESCRIPTION
**Pull request by gabemontero**
after analyzing must gather from https://github.com/openshift/csi-driver-shared-resource-operator/pull/17 and trading notes with @coreydaley, we now have the "collective" realization that these manifest files are irrelevant.

the (currently near) equivalents at https://github.com/openshift/cluster-storage-operator/tree/master/assets/csidriveroperators/shared-resource are the ones

@coreydaley is getting ready to broaden https://github.com/openshift/cluster-storage-operator/pull/229 to make sure  https://github.com/openshift/cluster-storage-operator/tree/master/assets/csidriveroperators/shared-resource has what we need, including the recent additions from @alicerum for metrics an my recent addition for the configuration configmap

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @coreydaley 

being paranoid, applied WIP label for now cause I want to double check must gather before we merge anything

**Comment by gabemontero** [comment]
also, don't want this to take effect until @coreydaley has the copies over to CSO in flight

**Comment by gabemontero** [comment]
> also, don't want this to take effect until @coreydaley has the copies over to CSO in flight

which @coreydaley  has up with https://github.com/openshift/cluster-storage-operator/pull/231

**Comment by coreydaley** [comment]
I think that this one can merge first, if I am missing something I can always get it from the previous commit.

**Comment by gabemontero** [comment]
so yeah tests passed and yeah I see various objects in the must gather 

that said, this gave me pause ... so I see this service monitor in the must gather:

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2021-11-01T19:27:33Z"
  generation: 1
  name: shared-resource-csi-driver-node
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "6337"
  uid: dd96d1c6-dd5e-449a-a8bc-4f5abf1bfe40
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: shared-resource-csi-driver-node

```

But that is one of the additions in @coreydaley 's https://github.com/openshift/cluster-storage-operator/pull/231/files#diff-ef4bf6daa1127f619d33f9cc575ff2d6df6605febb8c0505455a7e5af3b663e8

So I'm wondering, who is creating it?

Then I remembered that both the operator and driver have metrics endpoints, and I found https://github.com/openshift/csi-driver-shared-resource-operator/blob/master/assets/servicemonitor.yaml

I do not think both metrics endpoints can share the same servicemonitor.

So @coreydaley between you and @alicerum tomorrow while I'm out, you all will need to make sure the prometheus objects for both the operator and driver are uniquely named.

**Comment by gabemontero** [comment]
putting the /hold

we'll remove the WIP

@coreydaley I'm good with you removing the hold on this once the operator vs driver monitoring objects get sorted out

**Pull request merged**
