### PR TITLE
STOR-1441: Restart node Pods if metrics-serving-cert changed

### PR DESCRIPTION
**Pull request by mpatlasov**
Adding `WithSecretHashAnnotationHook()` for `shared-resource-csi-driver-node-metrics-serving-cert` ensures that new annotation is published in `shared-resource-csi-driver-node` DaemonSet. This, in turn, leads to node pods restart.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@mpatlasov out of curiosity, how often is this cert rotated in a typical OpenShift cluster? What is the impact in a large cluster (say 1,000 worker nodes)?

**Comment by Phaow** [comment]
Pre verifiy passed with the pre merged build `4.14.0-0.ci.test-2023-08-10-084739-ci-ln-t81vb0b-latest`

```console
# After the metrics-serving-cert secret changed, driver controller restarted
$ oc delete secret shared-resource-csi-driver-node-metrics-serving-cert
secret "shared-resource-csi-driver-node-metrics-serving-cert" deleted

$ oc get po -l app=shared-resource-csi-driver-node -w
NAME                                    READY   STATUS        RESTARTS   AGE
shared-resource-csi-driver-node-4r2lb   2/2     Terminating   2          40m
shared-resource-csi-driver-node-76s97   2/2     Running       0          11s
shared-resource-csi-driver-node-v8xqq   2/2     Running       0          40m
shared-resource-csi-driver-node-4r2lb   0/2     Terminating   2          40m
shared-resource-csi-driver-node-fchkb   0/2     Pending       0          0s
shared-resource-csi-driver-node-fchkb   0/2     Pending       0          0s
shared-resource-csi-driver-node-fchkb   0/2     Pending       0          0s
shared-resource-csi-driver-node-fchkb   0/2     ContainerCreating   0          0s
shared-resource-csi-driver-node-fchkb   0/2     ContainerCreating   0          0s
shared-resource-csi-driver-node-4r2lb   0/2     Terminating         2          40m
shared-resource-csi-driver-node-4r2lb   0/2     Terminating         2          40m
shared-resource-csi-driver-node-4r2lb   0/2     Terminating         2          40m
shared-resource-csi-driver-node-fchkb   2/2     Running             0          1s
shared-resource-csi-driver-node-v8xqq   2/2     Terminating         0          40m
shared-resource-csi-driver-node-v8xqq   0/2     Terminating         0          41m
shared-resource-csi-driver-node-j4mlm   0/2     Pending             0          0s
shared-resource-csi-driver-node-v8xqq   0/2     Terminating         0          41m
shared-resource-csi-driver-node-j4mlm   0/2     Pending             0          0s
shared-resource-csi-driver-node-j4mlm   0/2     Pending             0          0s
shared-resource-csi-driver-node-j4mlm   0/2     ContainerCreating   0          0s
shared-resource-csi-driver-node-v8xqq   0/2     Terminating         0          41m
shared-resource-csi-driver-node-v8xqq   0/2     Terminating         0          41m
shared-resource-csi-driver-node-j4mlm   0/2     ContainerCreating   0          0s
shared-resource-csi-driver-node-j4mlm   2/2     Running             0          1s

$ oc get po -l app=shared-resource-csi-driver-node
NAME                                    READY   STATUS    RESTARTS   AGE
shared-resource-csi-driver-node-76s97   2/2     Running   0          8m4s
shared-resource-csi-driver-node-fchkb   2/2     Running   0          7m31s
shared-resource-csi-driver-node-j4mlm   2/2     Running   0          6m59s
```

**Comment by jsafrane** [comment]
[Our doc](https://docs.openshift.com/container-platform/4.13/security/certificate_types_descriptions/service-ca-certificates.html#expiration) says OCP rotates certificates every 13 months, unless admins asks earlier

**Comment by mpatlasov** [comment]
Hi @adambkaplan , I updated the commit description with some words explaining why we need to restart pods. As for your previous questions, see please Jan's comment above: CA cert is rotated very rarely, once in 13 months. As for impact in a large cluster, TBH I can't see why we should expect severe impact: end-users will keep using their existing PVs while CSI driver pods restarting, and new CA cert is a big deal anyway.

**Pull request merged**
